"""User-level config loader for machine-specific paths.

设计:
- 单一 config 文件 ~/.codev-platform/config.json
- 字段全部可选, 缺失走代码默认 hardcode
- env 变量覆盖 config (用户可在 launcher .cmd 临时强制)
- 跨项目共享 — chroma daemon / index_docs / launcher 都读它

字段:
    models.embed_path        Qwen3-Embedding 模型目录
    models.embed_device      cuda / cpu
    models.reranker_path     Qwen3-Reranker 模型目录
    models.reranker_device   cuda / cpu
    models.reranker_enabled  true / false
    data.platform_data_dir   chroma / graph 共享基目录
    mcp.platform_docs_sse_port  chroma daemon HTTP 端口 (旧 daemon.port 为兼容别名)
    daemon.mode              true=daemon 共享 / false=每会话独立
    daemon.prewarm           启动期预热模型 (避免首次 query 60s 超时)
    search.recall_k          embedding 召回候选数 (rerank 前)
    search.return_k          最终返回数
    search.bm25_enabled      RRF 融合开关

用法:
    from codev_platform.core.config import load_config, get
    cfg = load_config()
    embed_path = get(cfg, "models.embed_path", default="...")
"""
from __future__ import annotations

import hashlib
import hmac
import json
import logging
import math
import os
import re
from pathlib import Path
from typing import Any


CONFIG_DIR_NAME = ".codev-platform"
CONFIG_FILE_NAME = "config.json"
DEFAULT_CONFIG_PATH = Path.home() / CONFIG_DIR_NAME / CONFIG_FILE_NAME
REINDEX_CONFIG_DIGEST_ENV = "CODEV_REINDEX_CONFIG_SHA256"
_SHA256_RE = re.compile(r"[0-9a-f]{64}\Z")


# 全字段默认 — config 文件 / env 未给时兜底。machine-agnostic: 模型路径默认 ~/models
# (Path.home() 各平台自解析: Win C:\Users\x\models / Mac /Users/x/models / Linux /home/x/models)。
# 换机器实际路径写进 ~/.codev-platform/config.json 覆盖, 代码里不留盘符字面量。
DEFAULTS: dict[str, Any] = {
    "models": {
        "embed_path": str(Path.home() / "models" / "Qwen3-Embedding-0.6B"),
        "embed_device": "cuda",
        "reranker_path": str(Path.home() / "models" / "Qwen3-Reranker-0.6B"),
        "reranker_device": "cuda",
        "reranker_enabled": True,
    },
    "data": {
        "platform_data_dir": None,  # None = 走 _business_repo_root cwd 推导
    },
    "daemon": {
        # 端口默认的单一真值源是 mcp_serve._bind_port (canonical 键 mcp.platform_docs_sse_port
        # > deprecated 别名 daemon.port > DEFAULT_CHROMA_PORT)。此处不再复制 daemon.port,
        # 否则默认 config 缺 canonical 键时会命中别名触发 deprecation warning。
        "mode": True,
        "prewarm": True,
    },
    "search": {
        "recall_k": 30,
        "return_k": 5,
        "bm25_enabled": True,
        "rrf_k_const": 60,
        "gpu_concurrency": 1,
    },
    "runtime": {
        # 正式变更必须由 CLI 显式传入或由用户配置填写；None 只允许开发只读回退。
        "release_root": None,
        "chroma_venv": None,  # chroma daemon 用的 venv 目录 (含 python.exe + mcp-proxy.exe). 必填.
    },
    "memory": {
        # 平台独立 PG 库 (codev_platform_memory) 连接串. 严禁复用业务库 DSN (见 memory plan §3.2b).
        # 密码走 env CODEV_PLATFORM_MEMORY_DSN 覆盖更安全; None = memory PG 未启用 (会话仅内存).
        "pg_dsn": None,
        # 读写分离扩展口 (预留, 不预建副本): 配只读副本 DSN 后读路径(get/has)自动走它,
        # 写路径(new/append)仍走 pg_dsn 主库. None = 读写同库 (单 PG 现状). 详见 memory plan §3.9。
        "pg_dsn_read": None,
        # M3 召回: 后端 "local"(直查 PG 结构化召回+冲突消解, 现状) | "vector"(chroma 语义排序, 数据量大时接,
        # 接缝已留见 recall_service.py). recall_limit = 注入 prompt 的最多记忆条数.
        "recall_backend": "local",
        "recall_limit": 8,
        # 冲突消解 policy (memory plan §3.5): "personal_first"(默认) | "org_first". 红线永远最高不可配.
        # M5 起改从 PG orgs.conflict_policy 读, 现为静态默认.
        "conflict_policy": "personal_first",
        # M4 压缩: 一个 (scope,topic) 攒到这么多条 active 记忆才触发 LLM 融合 (少于此不值得压).
        "compress_min_entries": 3,
        # PG 连接池每实例最大连接数. 多人并发高峰下 4 易撞 PoolTimeout; 默认 10, 按并发上调.
        "pool_max_size": 10,
    },
    "agent": {
        # 会话存储后端: "memory" (默认, 进程内, 重启丢) | "pg" (持久化到 memory.pg_dsn).
        "session_backend": "memory",
    },
    "systemd": {
        # Linux/WSL systemd units may load machine-local secrets and runtime env
        # from this optional EnvironmentFile. The file is never generated by
        # code and must stay outside git, e.g. /etc/codev-platform/platform.env.
        "env_file": None,
    },
    "reindex": {
        # 本机 FileSpoolQueue 默认: hook 入队后自动拉起短驻 worker。PG/服务器默认仍走
        # systemd 常驻 worker, 需显式 opt-in 才 auto-start。
        "worker_auto_start": True,
        "worker_auto_start_pg": False,
        "worker_idle_exit_sec": 600,
        "worker_heartbeat_sec": 10,
    },
    "project": {
        # Agent 项目配置查找顺序。迁移期默认 Codex 优先、Claude fallback。
        # 要切回 Claude 优先, 在 ~/.codev-platform/config.json 改为:
        # {"project": {"project_config_paths": [".claude/project.json", ".codex/project.json"]}}
        "project_config_paths": [".codex/project.json", ".claude/project.json"],
        # 文档索引配置查找顺序。避免把某个 agent 目录写死在代码里。
        "index_config_paths": [".codex/index.json", ".claude/index.json"],
    },
}


def _clone_defaults(defaults: dict[str, Any]) -> dict[str, Any]:
    """保持既有浅合并语义，避免显式配置上下文复用全局嵌套字典。"""
    return {key: dict(value) if isinstance(value, dict) else value for key, value in defaults.items()}


def _defaults_for_home(home: Path) -> dict[str, Any]:
    """返回指定服务账号 HOME 对应的动态默认配置。"""
    defaults = _clone_defaults(DEFAULTS)
    models = defaults["models"]
    if not isinstance(models, dict):  # pragma: no cover - DEFAULTS 的防御性契约
        raise RuntimeError("默认模型配置无效")
    models["embed_path"] = str(home / "models" / "Qwen3-Embedding-0.6B")
    models["reranker_path"] = str(home / "models" / "Qwen3-Reranker-0.6B")
    return defaults


def _normalize_config_home(home: Path | None) -> Path | None:
    """显式 home 只接受绝对路径，避免 root 安装器的相对路径上下文漂移。"""
    if home is None:
        return None
    if not isinstance(home, Path):
        raise TypeError("配置 home 必须是 Path")
    normalized = home.expanduser()
    if not normalized.is_absolute():
        raise ValueError("配置 home 必须是绝对路径")
    return normalized


def config_path(*, home: Path | None = None) -> Path:
    """env 可覆盖；显式 home 仅影响默认配置文件位置。"""
    configured = os.environ.get("CODEV_PLATFORM_CONFIG")
    if configured is not None:
        return Path(configured).expanduser()
    selected_home = _normalize_config_home(home)
    if selected_home is None:
        return DEFAULT_CONFIG_PATH
    return selected_home / CONFIG_DIR_NAME / CONFIG_FILE_NAME


def _canonical_config_value(value: object) -> None:
    if value is None or type(value) in {bool, int, str}:
        return
    if type(value) is float:
        if math.isfinite(value):
            return
        raise ValueError("配置快照包含非有限数")
    if type(value) is list:
        for item in value:
            _canonical_config_value(item)
        return
    if type(value) is dict:
        for key, item in value.items():
            if type(key) is not str:
                raise ValueError("配置快照包含非字符串键")
            _canonical_config_value(item)
        return
    raise ValueError("配置快照包含动态 Python 类型")


def config_snapshot_digest(cfg: dict[str, Any]) -> str:
    """计算不输出明文的完整配置摘要，忽略进程私有对象键。"""
    if type(cfg) is not dict:
        raise ValueError("配置快照必须是字典")
    public = {key: value for key, value in cfg.items() if type(key) is str}
    _canonical_config_value(public)
    try:
        encoded = json.dumps(
            public,
            ensure_ascii=True,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        ).encode("utf-8")
    except (TypeError, ValueError, UnicodeError):
        raise ValueError("配置快照无法规范编码") from None
    return hashlib.sha256(encoded).hexdigest()


def reindex_config_snapshot_environment(cfg: dict[str, Any]) -> dict[str, str]:
    """只向隔离子进程传配置摘要，不传可能含秘密的配置正文。"""
    return {REINDEX_CONFIG_DIGEST_ENV: config_snapshot_digest(cfg)}


def _verify_reindex_config_snapshot(cfg: dict[str, Any]) -> dict[str, Any]:
    expected = os.environ.get(REINDEX_CONFIG_DIGEST_ENV)
    if expected is None:
        return cfg
    if _SHA256_RE.fullmatch(expected) is None:
        raise RuntimeError("reindex 配置快照摘要无效")
    actual = config_snapshot_digest(cfg)
    if not hmac.compare_digest(actual, expected):
        raise RuntimeError("reindex 配置在 attempt 执行期间发生变化")
    return cfg


def load_config(*, home: Path | None = None) -> dict[str, Any]:
    """读 config 文件, merge 进 defaults (浅合并: 顶级 key 不覆盖, 子字段合并)。

    文件不存在 -> 全部走 defaults, 不抛异常 (这是支持的 "没配就默认")。
    文件存在但 JSON 解析失败 / 读取失败 -> 默认 fail-loud (logging.error + raise),
    避免配置损坏时静默退回默认/空配置带病运行 (如 token 鉴权静默失效)。
    逃生阀: 设 CODEV_CONFIG_IGNORE_ERRORS=1 才降级为 stderr 警告 + 返默认。

    ``home`` 只供 root 在生成某个服务账号的 systemd 声明时显式采用该账号的动态默认值；
    不改变当前进程 HOME，也不影响普通调用方。
    """
    selected_home = _normalize_config_home(home)
    cfg = _clone_defaults(DEFAULTS) if selected_home is None else _defaults_for_home(selected_home)
    p = config_path(home=selected_home)
    if not p.is_file():
        return _verify_reindex_config_snapshot(cfg)
    try:
        loaded = json.loads(p.read_text(encoding="utf-8"))
        for section, fields in loaded.items():
            if not isinstance(fields, dict):
                cfg[section] = fields
            elif section in cfg and isinstance(cfg[section], dict):
                cfg[section].update(fields)
            else:
                cfg[section] = fields
    except (json.JSONDecodeError, OSError) as exc:
        # 文件存在但损坏/不可读: 默认 fail-loud, 不静默退回默认 (防鉴权等关键配置静默失效)。
        ignore = os.environ.get("CODEV_CONFIG_IGNORE_ERRORS", "").strip().lower() in ("1", "true", "yes")
        if not ignore:
            logging.error(
                "[codev_platform.config] config 文件存在但损坏/不可读: %s (%s). "
                "拒绝带病运行; 设 CODEV_CONFIG_IGNORE_ERRORS=1 才降级返默认。",
                p, exc,
            )
            raise
        import sys
        print(
            f"[codev_platform.config] WARN: {p} 损坏或不可读, CODEV_CONFIG_IGNORE_ERRORS 已设, 全用默认值",
            file=sys.stderr, flush=True,
        )
    return _verify_reindex_config_snapshot(cfg)


def get(cfg: dict[str, Any], dotted_key: str, default: Any = None) -> Any:
    """读 'section.field' 形式的嵌套字段。"""
    cur: Any = cfg
    for part in dotted_key.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return default
        cur = cur[part]
    return cur


def env_or_config(env_var: str, cfg: dict[str, Any], dotted_key: str, default: Any = None) -> Any:
    """env var 优先, 否则 config, 否则 default。统一 daemon / index_docs / launcher 的解析。"""
    v = os.environ.get(env_var)
    if v is not None and v != "":
        return v
    return get(cfg, dotted_key, default)


def list_env_or_config(
    env_var: str,
    cfg: dict[str, Any],
    dotted_key: str,
    default: list[str] | tuple[str, ...],
) -> list[str]:
    """从 env/config 读取字符串列表。

    env 用分隔符列表,Windows 常用 `;`,其它平台按 `os.pathsep`。JSON config 推荐用字符串数组。
    """
    raw = os.environ.get(env_var)
    if raw:
        sep = ";" if ";" in raw else os.pathsep
        return [part.strip() for part in raw.split(sep) if part.strip()]
    value = get(cfg, dotted_key, list(default))
    if isinstance(value, str):
        return [value]
    if isinstance(value, (list, tuple)):
        return [str(part).strip() for part in value if str(part).strip()]
    return list(default)


def save_config(cfg: dict[str, Any], path: Path | None = None) -> Path:
    """保存 config 到文件 (创建父目录)。返回写入的路径。"""
    p = path or config_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(cfg, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return p
