/**
 * 拉后端枚举元数据 → 生成 src/models/enumslocal.tsx (与 stock-admin-web 同名机制)。
 * 运行: pnpm run enums (需后端 :18088 在跑)。
 *
 * 注: 本控制台的 enum.ts 已在运行时 post('/api/v1/enums/list') 动态加载枚举,
 * enumslocal 仅作类型/离线兜底, 非必需。第一版先留占位, 后端 Auth 波稳定后再完善。
 */
import axios from 'axios';
import { writeFileSync } from 'fs';
import { join } from 'path';

const BACKEND = process.env.CODEV_WEB_URL || 'http://127.0.0.1:18088';

async function main() {
  const { data } = await axios.post(`${BACKEND}/api/v1/enums/list`, {});
  const groups = data?.data ?? {};
  const out = `// AUTO-GENERATED by scripts/fetch-enums.ts — do not edit.\nexport const ENUMS = ${JSON.stringify(
    groups,
    null,
    2,
  )} as const;\n`;
  writeFileSync(join(__dirname, '../src/models/enumslocal.tsx'), out, 'utf-8');
  console.log(`[enums] wrote ${Object.keys(groups).length} enum types from ${BACKEND}`);
}

main().catch((e) => {
  console.error('[enums] failed:', e?.message || e);
  process.exit(1);
});
